version: '3.4'
services:
  web:
    build:
      context: cpoc-web/
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    volumes:
      - ./cpoc-web:/app
    command: bash -c "chmod +x entrypoint.sh && ./entrypoint.sh"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - 'redisdata:/data'

  celery:
    build:
      context: cpoc-web/
      dockerfile: Dockerfile.worker
    command: bash -c "chmod +x entrypoint-worker.sh && ./entrypoint-worker.sh"
    depends_on:
      - web

  queue-monitor:
    image: mher/flower
    command: flower --basic_auth=${QUEUE_MONITOR_USERNAME}:${QUEUE_MONITOR_PASSWORD} --address=0.0.0.0 --port=5555 --broker=redis://redis:6379
    ports:
      - '5555:5555'

volumes:
  redisdata:

